# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-BUFR
version:      1.15
version_from: lib/Geo/BUFR.pm
installdirs:  site
requires:
    Carp:                          0
    Config:                        0
    DynaLoader:                    0
    File::Slurp:                   0
    File::Spec::Functions:         0
    FileHandle:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0
    Storable:                      0
    Test::More:                    0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
